services:
  postgres:
    container_name: edc_pg
    image: postgres:17.4
    environment:
      POSTGRES_USER: cs
      POSTGRES_PASSWORD: cs
    ports:
      - "5432:5432"
    volumes:
      - "edc_data:/var/lib/postgresql/data"

volumes:
  edc_data:
