apiVersion: v1
kind: Service
metadata:
  name: {{ include "edc-tenant.controlplane" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "edc-tenant.controlplane" . }}
  ports:
    - name: web
      port: {{ .Values.ports.web }}
    - name: management
      port: {{ .Values.ports.management }}
      {{- include "edc-tenant.nodePort" (list . 81) | nindent 6 }}
    - name: protocol
      port: {{ .Values.ports.protocol }}
      {{- include "edc-tenant.nodePort" (list . 82) | nindent 6 }}
    - name: control
      port: {{ .Values.ports.control }}
    - name: catalog
      port: {{ .Values.ports.catalog }}
    - name: oid4vp
      port: {{ .Values.ports.oid4vp }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edc-tenant.dataplane" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "edc-tenant.dataplane" . }}
  ports:
    - name: control
      port: {{ .Values.ports.control }}
    - name: public
      port: {{ .Values.ports.public }}
      {{- include "edc-tenant.nodePort" (list . 92) | nindent 6 }}
